### ISSUE TITLE
R.flip example in documentation is wrong

### ISSUE THREAD

**Issue by MihailPertsev** [selfrefactor/rambda#566] opened 2021-02-21 15:03 UTC
Typo in documentation:
```
const subtractFlip = R.flip(R.subtract)

const result = [
  subtractFlip(1,7),
  R.flip(1, 6) // this should be R.subtract(1,7)
]  
```

**Comment by selfrefactor** [comment] 2021-02-22 11:07
will look into it. Thanks for the issue.

**Comment by selfrefactor** [comment] 2021-02-27 09:30
The issue is fixed. Closing

**Closed by selfrefactor** 2021-02-27 09:30 UTC
