### ISSUE TITLE
R.uniq is slower than Ramda for big arrays

### ISSUE THREAD

**Issue by bovine3dom** [selfrefactor/rambda#581] opened 2021-06-27 15:22 UTC
Minimal example:

```js
// Make an array of 10,000 strings with some repetition
let strings = R.map(() => Math.floor(Math.random() * 1000) + "", R.range(0,10000))

// Time R.uniq
const t0 = new Date().getTime()
R.uniq(strings)
const t1 = new Date().getTime()

// Store the result
const result = t1-t0
console.log(t1 - t0)
```

- in Ramda: ~1ms
- in Rambda: ~600ms

Related downstream issue: https://github.com/tridactyl/tridactyl/issues/3772

: )

**Comment by selfrefactor** [comment] 2021-06-28 07:50
I will run the code through Rambda benchmark and I'll get back to you.

**Comment by selfrefactor** [comment] 2021-06-28 08:52
Thank you @bovine3dom as this is a serious issue, which I can confirm. I will report again when there is a progress on this problem.

**Comment by selfrefactor** [comment] 2021-07-25 21:24
I have pinned the reason for this issue. Expect a fix with version `6.9.0`.

**Comment by selfrefactor** [comment] 2021-07-31 05:58
`6.9.0` was released with improved performance for `R.uniq` and several other related methods. I am closing the issue, but please feel free to comment further.

**Closed by selfrefactor** 2021-07-31 05:58 UTC

**Comment by selfrefactor** [comment] 2021-08-02 06:25
As a side note I am adding a bit more information about the result.

During developing the fix, I realized that underlying issue was lack of correct benchmarking process. As a result, there is now a new format for Rambda benchmark(https://github.com/selfrefactor/rambda/blob/master/source/benchmarks/uniq.js) which can produce dev-only benchmark result: https://github.com/selfrefactor/rambda-scripts/blob/master/scripts/run-benchmarks/benchmark-results/uniq.json

`UNIQ-ALL` key refers to the result used in README, while `UNIQ-0`, `UNIQ-1`, etc. refers to the index of `modes` list used to generate the benchmark.
