### ISSUE TITLE
types of path are breaking in 7.4.0

### ISSUE THREAD

**Issue by Retro64** [selfrefactor/rambda#668] opened 2022-12-06 08:51 UTC
When updating to version 7.4.0 from 7.3.0, the usage of path is breaking. In our code we use the un-curried version:

```
path<unknown>(['string','array'], object)
```

I do not see types for an un-curried version using `RamdaPath` - is this intended?

```
path<unknown>(['string','array'])(object)
```

works out.

I would have expected something like 

```
export function path<T>(pathToSearch: RamdaPath, obj: any) => T | undefined;
```

to be part of the types.

**Comment by selfrefactor** [comment] 2022-12-12 15:47
I will have a look and thanks for filling this issue.

**Comment by selfrefactor** [comment] 2022-12-15 22:49
Can you provide more detailed example just to be sure that issue is solved? I will restore what you suggest, but you are correct that 7.5.0 make changes to `R.path` types.

**Comment by Retro64** [comment] 2022-12-17 17:34
I tried do reproduce the error on my private machine, but was only able to reproduce it, if the path did not match the object. So I guess this issue can be closed  (and will do this with this comment) - sorry for the inconvenience @selfrefactor

**Comment by Retro64** [comment] 2023-01-04 08:19
I finally managed to reproduce it - I forgot the types on my local machine :

This works out:
```
import { path } from "rambda";

type unknownThis = {
    this: unknown
};

const object: unknownThis = {
    this: {
        is: {
            a: 'path'
        }
    }
};

const test1 = path(['this', 'is', 'not', 'a'])(object);

console.log(test1);
```

This doesn't:
```
import { path } from "rambda";

type unknownThis = {
    this: unknown
};

const object: unknownThis = {
    this: {
        is: {
            a: 'path'
        }
    }
};

const test1 = path(['this', 'is', 'not', 'a'], object);

console.log(test1);
```

**Comment by selfrefactor** [comment] 2023-01-05 16:14
I don't see it as error:

```
describe('R.path with array as path', () => {
  interface UnknownThis {
    this: unknown,
  }

  const object: UnknownThis = {
    this: {
      is: {
        a: 'path',
      },
    },
  }
  const test1 = path(['this', 'is', 'not', 'a'])(object)
  test1 // $ExpectType unknown
  const test21 = path(['this', 'is', 'not', 'a'], object)
  test21 // $ExpectType unknown
})
```

This test passes

**Comment by Retro64** [comment] 2023-01-06 07:09
May you test with type instead of interface again on 7.4.0?

**Comment by selfrefactor** [comment] 2023-01-06 08:57
`interface` is lint change; even before that it was the same. It might be from TS version, so let me know if that is the case. I will be closing the issue, but feel free to keep commenting. I cannot reproduce it, so I will close it for the time being.

**Comment by Retro64** [comment] 2023-01-08 22:06
![image](https://user-images.githubusercontent.com/11250054/211221298-f04339f1-f471-4798-aed9-56c2aaa7a9c0.png)

package.json
```
{
  "name": "rambda-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "tsc src/*"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "rambda": "7.4.0",
    "typescript": "4.9.4"
  }
}
```

tsconfig
```
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict":true
  }
}

```

**Comment by selfrefactor** [comment] 2023-01-09 08:26
thanks, that helped. It was hard for me to reproduce it, but I finally managed. Fix is applied and it will be released with next version. Thanks for the efforts.

**Comment by Retro64** [comment] 2023-01-09 12:28
Thanks for your fast replies and your dedication. Just gives the feeling we choose the right lib :)

**Comment by selfrefactor** [comment] 2023-03-03 15:30
release is made so I am closing this issue

**Closed by selfrefactor** 2023-03-03 15:30 UTC
Labels: done waiting release
