### ISSUE TITLE
[BUG] `isEmpty` not checking for nullish values

### ISSUE THREAD

**Issue by RoyRao2333** [selfrefactor/rambda#739] opened 2024-07-24 07:00 UTC
**Describe the bug**

Just jumped from lodash to rambda. Great work by the way!

In lodash or radash, `isEmpty` will return `true` if the value itself is nullish:

<img width="905" alt="image" src="https://github.com/user-attachments/assets/fc42843f-288a-4410-b943-9cc845bfb833">

<img width="647" alt="image" src="https://github.com/user-attachments/assets/98295b2a-36b3-4a19-a2fe-7bddd7bc517c">

But I noticed that `isEmpty` in rambda skipped nullish values like `undefined` or `null`, which is a little counterintuitive for me :

<img width="538" alt="image" src="https://github.com/user-attachments/assets/717087ee-e582-4ef1-bde7-a9f59cef257c">

Is this intensional or am I using this util wrong?

**Context(which version of library)**

rambda@9.2.1

**Comment by selfrefactor** [comment] 2024-07-24 09:43
I will check and get back to you. Txs for the nice words!

**Comment by selfrefactor** [comment] 2024-07-26 19:05
I will close it as this work as intended, i.e. it matches Ramda logic:


```
import { isEmpty } from 'ramda'
// import { isEmpty } from './isEmpty.js'

test('happy', () => {
  expect(isEmpty(undefined)).toBeFalse()
  expect(isEmpty('')).toBeTrue()
  expect(isEmpty(null)).toBeFalse()
  expect(isEmpty(' ')).toBeFalse()
  expect(isEmpty(new RegExp(''))).toBeFalse()
  expect(isEmpty([])).toBeTrue()
  expect(isEmpty([ [] ])).toBeFalse()
  expect(isEmpty({})).toBeTrue()
  expect(isEmpty({ x : 0 })).toBeFalse()
  expect(isEmpty(0)).toBeFalse()
  expect(isEmpty(NaN)).toBeFalse()
  expect(isEmpty([ '' ])).toBeFalse()
 ```

**Closed by selfrefactor** 2024-07-26 19:05 UTC
