### ISSUE TITLE
use  import * as R from "https://deno.land/x/rambda/rambda.js"

### ISSUE THREAD

**Issue by pinghe** [selfrefactor/rambda#596] opened 2021-08-18 01:22 UTC
In the deno environment, it is not possible to use import * as R from "https://deno.land/x/rambda/rambda.js", because the file rambda.js is missing from https://deno.land/x/rambda,

**Comment by selfrefactor** [comment] 2021-08-18 08:15
Thanks for the report. I'll check what can be done for it. Can you share why you are opting to use `import * as R` instead of importing only the methods you will be using?

**Comment by pinghe** [comment] 2021-08-18 11:18
Testing, Learning

**Comment by selfrefactor** [comment] 2021-08-18 12:07
In this case, I'll check if Ramda and Lodash provides such option for their deno builds. I am asking as I used `import * as R` only before realizing that this pattern has problems. I'll write back when I have more info.

**Comment by pinghe** [comment] 2021-08-20 00:18
ramda
```
import * as R from "https://deno.land/x/ramda/mod.ts"
```

**Comment by selfrefactor** [comment] 2021-08-20 13:48
From what I see in https://github.com/ramda/ramda/pull/3054/files, the issue is more about `nest.land` support. In this case, I'd rather skip the request for now. If you agree, let us wait a bit until more people using Deno share their opinion on the matter and then we can either dismiss the request or make the appropriate changes.

**Comment by pinghe** [comment] 2021-08-23 08:47
https://github.com/ramda/ramda/blob/master/README.md

Installation
------------

To use with node:

```bash
$ npm install ramda
```

Then in the console:

```javascript
const R = require('ramda');
```

To use directly in [Deno](https://deno.land):
```javascript
import * as R from "https://deno.land/x/ramda@v0.27.2/mod.ts";
```

or using Nest.land:
```javascript
import * as R from "https://x.nest.land/ramda@0.27.2/mod.ts";
```

**Comment by selfrefactor** [comment] 2021-08-23 12:45
I saw that as well, but I have some questions as I cannot see enough value for Rambda integration with Nest.land as I don't use Deno yet.

In this case, I think to create a process that builds `rambda.ts` file inside `src` folder, instead of using `mod.ts` file. Also, I have some other tasks before moving to this one, so I cannot close the issue so quickly and I hope you patient enough; it will happen.

**Comment by pinghe** [comment] 2021-08-24 00:21
thank you.

**Comment by selfrefactor** [comment] 2021-09-21 12:07
I am currently in a sick leave, but afterwards I will look into the issue.

**Comment by selfrefactor** [comment] 2022-03-01 10:48
So I did published 7.0.3 as 7.0.4 on Nest.land
This means that this example works:

```
import {add} from "https://x.nest.land/rambda@7.0.4/src/add.js";

function totalCost(outbound: any, inbound: any){
  return add(outbound, inbound)
}

console.log(totalCost(19, 31));
console.log(totalCost(45, 27));
```

however, this doesn't work for me, so you can tell me if it works for you:

```
import * as R from "https://x.nest.land/rambda@7.0.4/mod.ts";

function totalCost(outbound: any, inbound: any){
  return R.add(outbound, inbound)
}

console.log(totalCost(19, 31));
console.log(totalCost(45, 27));
```

**Comment by selfrefactor** [comment] 2022-03-01 16:54
I manage to find the cause of the issue and it test version `7.0.5` works correctly with Nestland.

The issue is that I will have to make changes to lint process as the issue was with import with extension ESLint rule.

I am not closing the issue until lint process if fixed for Deno.

**Comment by selfrefactor** [comment] 2022-05-06 11:35
I am closing the issue as version `7.1.0` is published to Nest.land

**Closed by selfrefactor** 2022-05-06 11:35 UTC
Labels: in progress
