### ISSUE TITLE
A bit wrong explanation in readme

### ISSUE THREAD

**Issue by the-phoenix** [selfrefactor/rambda#88] opened 2018-12-06 15:29 UTC
<img width="1439" alt="screen shot 2018-12-06 at 11 27 06 pm" src="https://user-images.githubusercontent.com/9201924/49593497-a6087d00-f9ae-11e8-913a-db5fa3cdb268.png">

Please look attached. 
Its comparing object references, not the contents of the object. 
`expectedResult` isn't same with `result`

**Comment by selfrefactor** [comment] 2018-12-06 16:13
So the issue is with the last line of the example.
If you  type `console.log(R.equals(result,expectedResult))` the log will be true. It is an issue and it will be addressed as there may be other examples that need such change to `R.equals`

**Comment by selfrefactor** [comment] 2018-12-06 16:22
I am closing the issue, but feel free to comment if there is such need.

**Closed by selfrefactor** 2018-12-06 16:22 UTC
