### ISSUE TITLE
R.uniq should not convert undefined to null in Rambda REPL

### ISSUE THREAD

**Issue by alexander-entin** [selfrefactor/rambda#576] opened 2021-05-06 13:15 UTC
R.uniq([undefined, null])
// expected result: [undefined, null]
// actual result: [null, null]
// (at least in the [playground)](https://rambda.vercel.app/?const%20result%20%3D%20R.uniq(%5Bundefined%2C%20null%5D))

**Comment by selfrefactor** [comment] 2021-05-09 08:38
It seems that the issue is related to REPL as I added a new test case in `uniq.spec.js` and it looks that it is working correctly. I will write again once I understand why this happens only in REPL.

**Comment by selfrefactor** [comment] 2021-05-09 09:12
The reason is that `JSON.stringify([null, undefined])` is equal to `[null, null]` and REPL app is using `JSON.stringify` . I will keep the issue open until I solve the issue.

**Comment by selfrefactor** [comment] 2021-09-21 12:08
I am currently in a sick leave, but afterwards I will look into the issue.

**Comment by selfrefactor** [comment] 2021-12-03 20:10
Thanks for the issue; it is fixed now.

**Closed by selfrefactor** 2021-12-03 20:10 UTC
Labels: REPL
