### ISSUE TITLE
Unknown plugin "external-helpers"

### ISSUE THREAD

**Issue by jpgorman** [selfrefactor/rambda#60] opened 2018-02-02 09:59 UTC
I've noticed that you now have to set the NODE_ENV variable in your process when using the package, otherwise you get the following error.

Module build failed: ReferenceError: Unknown plugin "external-helpers" specified in "/home/travis/build/jpgorman/react-append-to-body/node_modules/rambda/.babelrc.env.development"

**Comment by selfrefactor** [comment] 2018-02-02 19:07
That may be the reason for a bug I have when using it with `Parcel`. 
Nice catch @jpgorman I will look into it.

**Comment by selfrefactor** [comment] 2018-02-02 19:23
So, I have trouble reproducing this bug. I can confirm that I have seen the same error when I use `Rambda` with `Parcel` but when I opened issue there, it was admitted as bug on `Parcel` side.

This code doesn't produce the bug:
```
process.env = {}

const R = require('rambda')
console.log(process.env.NODE_ENV, R.add(1,1));
```

Let me know how I can reproduce it, as now it is hard for me to take an action.

**Comment by jpgorman** [comment] 2018-02-05 10:02
I've used a webpack config as we need to transpile the es6 from the rambda library as part of the build chain. 

I've then managed to resolve the issue by adding the `export NODE_ENV=production && ./node_modules ......`

So essentially it looks as though the development env for rambda has some missing dependencies, which show up when you build without specifiying the NODE_ENV as babel preset will default to the dev env if none is specified.

**Comment by selfrefactor** [comment] 2018-02-05 10:07
Thanks for your input. I cloned your repo and it works as you described. So now I can play with '.babelrc' and figure out a solution.

**Comment by selfrefactor** [comment] 2018-02-06 07:51
So according to [https://babeljs.io/docs/usage/babelrc/](https://babeljs.io/docs/usage/babelrc/) it defaults to development when no NODE_ENV is set. So now the build is requires NODE_ENV=build and thus we bypass the external-helpers issue. 

Thanks for your efforts in closing this @jpgorman

**Closed by selfrefactor** 2018-02-06 07:51 UTC
