### ISSUE TITLE
[BUG] the deno instructions don't work

### ISSUE THREAD

**Issue by freefrancisco** [selfrefactor/rambda#731] opened 2024-05-17 12:22 UTC
**Describe the bug**

I was trying to test Rambda in a deno app to see if I want to replace Ramda with it, but the deno.land download is not working. 
In a script I tried importing it like the documentation indicates:

`import * as R from "https://deno.land/x/rambda/mod.ts";`

but trying to run the script I get this error:
```
Warning Implicitly using latest version (v9.2.0) for https://deno.land/x/rambda/mod.ts
error: Module not found "https://deno.land/x/rambda@v9.2.0/src/prop".
    at https://deno.land/x/rambda@v9.2.0/src/hasIn.js:1:24
```

**Context(which version of library)**

This happened also when trying to import v9.2.0 and v9.1.1 explicitly

**Comment by selfrefactor** [comment] 2024-05-20 17:09
Thanks for filling this bug; I will look into it and get back to you.

**Comment by selfrefactor** [comment] 2024-05-28 18:58
Found the issue. I am making release today, so let's see if it works.

**Comment by selfrefactor** [comment] 2024-11-05 19:36
Finally, the issue is fixed with https://deno.land/x/rambda@9.4.1

Now, this `import * as R from 'https://deno.land/x/rambda@9.4.1/mod.ts'` works

**Closed by selfrefactor** 2024-11-05 19:36 UTC
Labels: bug
