### ISSUE TITLE
R.once TS type definition miss to context argument and its type 

### ISSUE THREAD

**Issue by jerome-benoit** [selfrefactor/rambda#728] opened 2024-03-11 22:43 UTC
**Describe the bug**

Rambda type: ```export function once<T extends AnyFunction>(func: T): T;```

And the expected type is more: 

```ts
export const once = <T extends AnyFunction, C = unknown>(
  fn: T,
  context?: C
): T
```

**Context(which version of library)** 
9.1.1

**Comment by selfrefactor** [comment] 2024-03-18 10:17
Not a bug as Rambda typings are same as Ramda. Still, I will add this and it will be released with next version. I will write once it is done.

**Comment by jerome-benoit** [comment] 2024-03-18 11:10
The proposed type definition including the complete `once()` function arguments is backward compatible with the previous one. Without it, one can't bound it to another instance if using typescript without `tsc` error, which is a legit use case. 

Thanks.

**Comment by selfrefactor** [comment] 2024-03-27 15:12
txs for clarification; in this case I will add it and release it.

**Comment by selfrefactor** [comment] 2024-04-02 08:32
Released with `9.2.0`

**Closed by selfrefactor** 2024-04-02 08:32 UTC
Labels: in progress
